//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 02:50:55 PM IST 
//


package com.employeedetails.jaxb.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salary-information complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salary-information">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="basic-pay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hra-pay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="da-pay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salary-information", propOrder = {
    "basicPay",
    "hraPay",
    "daPay"
})
public class SalaryInformation {

    @XmlElement(name = "basic-pay")
    protected String basicPay;
    @XmlElement(name = "hra-pay")
    protected String hraPay;
    @XmlElement(name = "da-pay")
    protected String daPay;

    /**
     * Gets the value of the basicPay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasicPay() {
        return basicPay;
    }

    /**
     * Sets the value of the basicPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasicPay(String value) {
        this.basicPay = value;
    }

    /**
     * Gets the value of the hraPay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHraPay() {
        return hraPay;
    }

    /**
     * Sets the value of the hraPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHraPay(String value) {
        this.hraPay = value;
    }

    /**
     * Gets the value of the daPay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaPay() {
        return daPay;
    }

    /**
     * Sets the value of the daPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaPay(String value) {
        this.daPay = value;
    }

}
