//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 02:51:55 PM IST 
//


package com.employeedetails.jaxb.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for employee-salary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="employee-salary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="earnings-total" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deductions" type="{}deductions" minOccurs="0"/>
 *         &lt;element name="total-payout" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employee-salary", propOrder = {
    "id",
    "earningsTotal",
    "deductions",
    "totalPayout"
})
public class EmployeeSalary {

    protected String id;
    @XmlElement(name = "earnings-total")
    protected String earningsTotal;
    protected Deductions deductions;
    @XmlElement(name = "total-payout")
    protected String totalPayout;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the earningsTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarningsTotal() {
        return earningsTotal;
    }

    /**
     * Sets the value of the earningsTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarningsTotal(String value) {
        this.earningsTotal = value;
    }

    /**
     * Gets the value of the deductions property.
     * 
     * @return
     *     possible object is
     *     {@link Deductions }
     *     
     */
    public Deductions getDeductions() {
        return deductions;
    }

    /**
     * Sets the value of the deductions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deductions }
     *     
     */
    public void setDeductions(Deductions value) {
        this.deductions = value;
    }

    /**
     * Gets the value of the totalPayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalPayout() {
        return totalPayout;
    }

    /**
     * Sets the value of the totalPayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalPayout(String value) {
        this.totalPayout = value;
    }

}
