//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 02:51:55 PM IST 
//


package com.employeedetails.jaxb.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employee-salary" type="{}employee-salary" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "employeeSalary"
})
@XmlRootElement(name = "employee-response")
public class EmployeeResponse {

    @XmlElement(name = "employee-salary")
    protected EmployeeSalary employeeSalary;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the employeeSalary property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeSalary }
     *     
     */
    public EmployeeSalary getEmployeeSalary() {
        return employeeSalary;
    }

    /**
     * Sets the value of the employeeSalary property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeSalary }
     *     
     */
    public void setEmployeeSalary(EmployeeSalary value) {
        this.employeeSalary = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
